apiVersion: v1
kind: Service
metadata:
  name: frontend-medical-record
  labels:
    app: frontend-medical-record
spec:
  # Tipo de servicio: NodePort para exponer el frontend fuera del cl√∫ster
  type: NodePort
  selector:
    app: frontend-medical-record
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30561
    protocol: TCP
    name: http
